export const allStudents = [
    {
        id: "1",
        name: "Alex Johnson",
        grade: "10th",
        attendanceToday: true,
        attendanceRate: "95%",
        image: "/placeholder.svg",
    },
    {
        id: "2",
        name: "Jamie Smith",
        grade: "10th",
        attendanceToday: false,
        attendanceRate: "87%",
        image: "/placeholder.svg",
    },
    {
        id: "3",
        name: "Taylor Brown",
        grade: "10th",
        attendanceToday: true,
        attendanceRate: "92%",
        image: "/placeholder.svg",
    },
    {
        id: "4",
        name: "Morgan Davis",
        grade: "10th",
        attendanceToday: true,
        attendanceRate: "98%",
        image: "/placeholder.svg",
    },
    {
        id: "5",
        name: "Riley Wilson",
        grade: "10th",
        attendanceToday: false,
        attendanceRate: "78%",
        image: "/placeholder.svg",
    },
    {
        id: "6",
        name: "Casey Miller",
        grade: "10th",
        attendanceToday: true,
        attendanceRate: "91%",
        image: "/placeholder.svg",
    },
    {
        id: "7",
        name: "Jordan Garcia",
        grade: "10th",
        attendanceToday: true,
        attendanceRate: "94%",
        image: "/placeholder.svg",
    },
]